name: Deploy Documentation
on:
  push:
    branches: [main, dev]
    tags: ['v*']
permissions:
  contents: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install dependencies
        run: |
          uv venv
          uv sync --dev
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: Initialize cache
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Deploy
        run: |
          source .venv/bin/activate
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            VER="${GITHUB_REF#refs/tags/v}"
            mike deploy --push "$VER"
          elif [[ "$GITHUB_REF" == refs/heads/main ]]; then
            mike deploy --push --update-aliases latest
            mike set-default --push latest
          else
            mike deploy --push dev
          fi
